apiVersion: apps/v1
kind: Deployment
metadata:
  name: lala-deployment
spec:
  selector:
    matchLabels:
      app: lala
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: lala
    spec:
      containers:
      - name: lala
        image: lala:1.0.0
        ports:
        - containerPort: 8000
